name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Home Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/jang/bookai
            git pull origin main
            pnpm install
            pnpm build
            sudo systemctl reload nginx
      - name: Discord notification
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "bookai 프론트엔드 배포"
          description: |
              **커밋**: `${{ github.event.head_commit.message }}`
              **작성자**: ${{ github.event.head_commit.author.name }}
          username: GitHub Actions
            
